# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_server/service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpc_server/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_server/service.proto\x12\x05\x65vent\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63oefficient\x18\x03 \x01(\x01\x12,\n\x08\x64\x65\x61\x64line\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x06status\x18\x05 \x01(\x0e\x32\x12.event.EventStatus\")\n\x15\x45ventExistenceRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\"%\n\x13\x45ventExistenceReply\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"#\n\x0fGetEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\"<\n\x13GetAllEventsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"M\n\x14GetAllEventsResponse\x12\x1c\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x0c.event.Event\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t*d\n\x0b\x45ventStatus\x12\x1c\n\x18\x45VENT_STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTART_WAITING\x10\x01\x12\x0e\n\nIN_PROCESS\x10\x02\x12\t\n\x05WIN_1\x10\x03\x12\t\n\x05WIN_2\x10\x04\x32\xe0\x01\n\x15\x45ventExistenceService\x12L\n\x10\x43heckEventExists\x12\x1c.event.EventExistenceRequest\x1a\x1a.event.EventExistenceReply\x12\x30\n\x08GetEvent\x12\x16.event.GetEventRequest\x1a\x0c.event.Event\x12G\n\x0cGetAllEvents\x12\x1a.event.GetAllEventsRequest\x1a\x1b.event.GetAllEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSTATUS']._serialized_start=453
  _globals['_EVENTSTATUS']._serialized_end=553
  _globals['_EVENT']._serialized_start=69
  _globals['_EVENT']._serialized_end=191
  _globals['_EVENTEXISTENCEREQUEST']._serialized_start=193
  _globals['_EVENTEXISTENCEREQUEST']._serialized_end=234
  _globals['_EVENTEXISTENCEREPLY']._serialized_start=236
  _globals['_EVENTEXISTENCEREPLY']._serialized_end=273
  _globals['_GETEVENTREQUEST']._serialized_start=275
  _globals['_GETEVENTREQUEST']._serialized_end=310
  _globals['_GETALLEVENTSREQUEST']._serialized_start=312
  _globals['_GETALLEVENTSREQUEST']._serialized_end=372
  _globals['_GETALLEVENTSRESPONSE']._serialized_start=374
  _globals['_GETALLEVENTSRESPONSE']._serialized_end=451
  _globals['_EVENTEXISTENCESERVICE']._serialized_start=556
  _globals['_EVENTEXISTENCESERVICE']._serialized_end=780
# @@protoc_insertion_point(module_scope)
