# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_server import service_pb2 as grpc__server_dot_service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_server/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventExistenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckEventExists = channel.unary_unary(
                '/event.EventExistenceService/CheckEventExists',
                request_serializer=grpc__server_dot_service__pb2.EventExistenceRequest.SerializeToString,
                response_deserializer=grpc__server_dot_service__pb2.EventExistenceReply.FromString,
                _registered_method=True)
        self.GetEvent = channel.unary_unary(
                '/event.EventExistenceService/GetEvent',
                request_serializer=grpc__server_dot_service__pb2.GetEventRequest.SerializeToString,
                response_deserializer=grpc__server_dot_service__pb2.Event.FromString,
                _registered_method=True)
        self.GetAllEvents = channel.unary_unary(
                '/event.EventExistenceService/GetAllEvents',
                request_serializer=grpc__server_dot_service__pb2.GetAllEventsRequest.SerializeToString,
                response_deserializer=grpc__server_dot_service__pb2.GetAllEventsResponse.FromString,
                _registered_method=True)


class EventExistenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckEventExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventExistenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckEventExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckEventExists,
                    request_deserializer=grpc__server_dot_service__pb2.EventExistenceRequest.FromString,
                    response_serializer=grpc__server_dot_service__pb2.EventExistenceReply.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=grpc__server_dot_service__pb2.GetEventRequest.FromString,
                    response_serializer=grpc__server_dot_service__pb2.Event.SerializeToString,
            ),
            'GetAllEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllEvents,
                    request_deserializer=grpc__server_dot_service__pb2.GetAllEventsRequest.FromString,
                    response_serializer=grpc__server_dot_service__pb2.GetAllEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'event.EventExistenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('event.EventExistenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventExistenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckEventExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event.EventExistenceService/CheckEventExists',
            grpc__server_dot_service__pb2.EventExistenceRequest.SerializeToString,
            grpc__server_dot_service__pb2.EventExistenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event.EventExistenceService/GetEvent',
            grpc__server_dot_service__pb2.GetEventRequest.SerializeToString,
            grpc__server_dot_service__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event.EventExistenceService/GetAllEvents',
            grpc__server_dot_service__pb2.GetAllEventsRequest.SerializeToString,
            grpc__server_dot_service__pb2.GetAllEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
